# Generated by Django 4.0.4 on 2022-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='color',
            field=models.CharField(default='Белый', max_length=200),
        ),
        migrations.AddField(
            model_name='cup',
            name='image',
            field=models.ImageField(default='1_aLvXjS4.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='cup',
            name='size',
            field=models.CharField(default='Большой', max_length=200),
        ),
        migrations.AddField(
            model_name='cup',
            name='surface',
            field=models.CharField(default='Гладкая', max_length=200),
        ),
        migrations.AddField(
            model_name='cup',
            name='type',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
